# This workflow will do a clean installation of node dependencies, cache/restore them and build the source code
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@35ab4267a1a21c8e8cb1c087cf1642e891ff57bd
        uses: pnpm/action-setup@v2.2.1
        with:
          # Version of PNPM to install
          version: 7.0.0-rc.8 # optional
          # Where to store PNPM files
          # dest: # optional, default is ~/setup-pnpm
          # If specified, run `pnpm install`
          run_install: true # optional, default is null
      - run: pnpm run build --if-present
      - run: cp -r src/static docs/
